### ISSUE TITLE
mainLocalFolder needs a path that is configured in conf.json

### ISSUE THREAD

**Issue by kilduff** [ExLibrisGroup/AlmaRemoteStorageApp#11]
"static String mainLocalFolder" is used in both com.exlibris.request.RequestsMain.java and in com.exlibris.items.ItemsMain.java.   These string do not provide a path to the locations of the folders. 

Perhaps if you add a "mainLocalPath" in the conf.json and concatenated mainLocalPath + mainLocalFolder files would be put in the proper place.  Otherwise the app has no way of knowing where the mainLocalFolder should be.  Currently we are having the files placed under /opt/local/scf/files.

Please let me know if you have any questions.

thanks,
Kathy

**Comment by ori229** [comment]
Hi Kathy,
As you suggested, we added a field to conf.json: main_local_folder
See the changes here: https://github.com/ExLibrisGroup/AlmaRemoteStorageApp/commit/74c173e838ad0949acc8b035e4510ff6fe525827
Thanks,
Yehudit & Ori
