### ISSUE TITLE
Server set up question - tomcat version?

### ISSUE THREAD

**Issue by kilduff** [ExLibrisGroup/AlmaRemoteStorageApp#2]
I am starting to install software for the server that will host the remote storage app.  I have several questions on versions of software.

What version of Tomcat do you recommend?  I notice that your configuration specifies webapp-runner version 8.0.30.2.  (See below)

<configuration>
	<artifactItems>
		<artifactItem>
			<groupId>com.github.jsimone</groupId>
			<artifactId>webapp-runner</artifactId>
			<version>8.0.30.2</version>
			<destFileName>webapp-runner.jar</destFileName>
		</artifactItem>
	</artifactItems>
</configuration>

I believe that webapp-runner versions are set to map to the tomcat version that it relies on.  Tomcat 8.0.x has been superseded and the tomcat8.0 branch of webapp-runner is deprecated.   Is there any specific reason we would need to use Tomcat 8.0?

Also, what version of java have you been using?    Java * or a later version?  If it is 8 will install an earlier version of maven.

thanks,
Kathy

**Comment by orenfarkas** [comment]
There is no dependency on a specific Tomcat or Java version.
The most up to date versions can be used

**Comment by dongourley** [comment]
You can close this issue.
