### ISSUE TITLE
Q: conf.json for the remote storage IZ

### ISSUE THREAD

**Issue by dongourley** [ExLibrisGroup/AlmaRemoteStorageApp#3]
In the example conf.json file there is a list of `institutions`, the first being `01AAA_RS` with lib code RS and location `rs_shared`, and no `*_job_id parameters`. This duplicates the example values at the beginning of the file for `remote_storage_*` parameters, which we are specifying for the WRLC Shared Collections Facility (SCF). 

Do we repeat that information for the SCF in the `institutions` list?

**Comment by YehuditAdler** [comment]
You are right, no need to repeat,
All that we need for the remote storage exists in the beginning.
we updated the conf.json accordingly.
