### ISSUE TITLE
Q: Alma Shared Secret for webhook

### ISSUE THREAD

**Issue by kilduff** [ExLibrisGroup/AlmaRemoteStorageApp#4]
Hi,

I do not see where the AlmaRemoteStorageApp webhook code validates the post request signature.  Shouldn't a shared secret used?  If so, where would it be configured for the AlmaRemoteStorageApp?  In conf.json?

thanks,
Kathy

**Comment by ori229** [comment]
Hi Kathy,
We will look into adding support for it in the App. In the meantime you can configure the Webhook profiles in Alma with some random characters as a password.
I'll update here once it is done.
Ori
Alma API Team

**Comment by ori229** [comment]
Done.
You'll need to choose a password, write it down in conf.json under webhook_secret and in all webhook profiles.
