### ISSUE TITLE
Question about job ID(s) for conf.json

### ISSUE THREAD

**Issue by dongourley** [ExLibrisGroup/AlmaRemoteStorageApp#5]
I configured a Remote Storage Integration Profile named "**Shared Collections Facility**" in each IZ. 

**please confirm:**

Is the name of the job (from the jobs API call) that I want to get the "publishing_job_id" from named "Inventory Remote Storage Update - **Shared Collections Facility**"?

Is the name of the job to get the "requests_job_id" named "Send Requests to Remote Storage"?

**why I'm asking (tl;dr):**

conf.json has a space for two job IDs for each IZ:
```
    "requests_job_id":"S123456789",
    "publishing_job_id":"S987654321",
```
The instructions say "Find the job ID [singular] ... use this API ... search for the integration profile name and get the id." 

I got the /almaws/v1/conf/jobs for each IZ. The only place I can find the name of the Remote Storage integration profile is in the name & desc for a "Repository" job:
```
    "name": "Inventory Remote Storage Update - Shared Collections Facility",
```
So I assume that is the publishing job id.

I also found a "Fulfillment" job about "Remote Storage":
```
    "name": "Send Requests to Remote Storage"
```
That must be the requests job id, even tho it doesn't have "Shared Collections Facility" in it?

**Comment by ori229** [comment]
Thanks for the question. The documentation wasn't clear - we improved it now.
requests_job_id is for the Remote Storage Facility requests export job.
publishing_job_id is for the Item publishing job.

**Comment by dongourley** [comment]
Thanks for the improved documentation, esp. the expanded instructions for all institutions step 4. It could be clearer if the 4th bullet said which Profile ID you run the jobs?profile_id={ID} against -- I assume it is the Publishing Profile ID (not the RS integration profile ID)?

The requests_job_id instruction (step 3, bullet 3) is referring, I assume, to the Remote Storage Integration Profile ID. It says to 'grab the profile ID from the "i" in the UI' but there is no ID in the info pop-up on the RS integration profile ID:
![i-in-the-ui](https://user-images.githubusercontent.com/282597/69079171-698b3100-0a07-11ea-8220-76f5dfaf87b6.png)

And since step 3 is "To export all requests to remote storage" shouldn't the job I'm looking for be the one named "Send Requests to Remote Storage" -- not 'the job whose name starts with “Inventory Remote Storage Update”'?

**Comment by ori229** [comment]
1. For the publishing job - the ID of the Publishing Profile.
For the Remote storage job - the ID of its Integration Profile.
2. If the ID doesn't show up under the "i" we'll need to use an API for it: /almaws/v1/conf/integration-profiles?type=REMOTE_STORAGE - I'll update the doc.
3. Please use the job which starts with “Inventory Remote Storage Update”'.
