### ISSUE TITLE
Compilation failue - argument lists differ (SCFUtil, ItemApi)

### ISSUE THREAD

**Issue by kilduff** [ExLibrisGroup/AlmaRemoteStorageApp#6]
I was not able to build app due to mismatch of arguments between SCFUtil and ItemApi.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project AlmaRemoteStorageApp: Compilation failure
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/util/SCFUtil.java:[368,44] method scanIn in class com.exlibris.restapis.ItemApi cannot be applied to given types;
[ERROR]   required: java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String
[ERROR]   found: java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String
[ERROR]   reason: actual and formal argument lists differ in length

**Comment by ori229** [comment]
Apologies - one file (ItemApi .java) wasn't updated on Git. 
Now all should be fine. We also added a few debug messages to help troubleshoot issues.
