### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by kilduff** [ExLibrisGroup/AlmaRemoteStorageApp#7]
It appears that the pom.xml file was not updated and a dependency is missing.  Could you please update?

Here is a portion of the error messages:
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[15,23] package com.jcraft.jsch does not exist
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[16,35] package com.jcraft.jsch.ChannelSftp does not exist
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[17,23] package com.jcraft.jsch does not exist
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[18,23] package com.jcraft.jsch does not exist
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[19,23] package com.jcraft.jsch does not exist
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[20,23] package com.jcraft.jsch does not exist
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[21,23] package com.jcraft.jsch does not exist
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[22,23] package com.jcraft.jsch does not exist
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[27,17] cannot find symbol
  symbol:   class ChannelSftp
  location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[29,16] cannot find symbol
  symbol:   class ChannelSftp
  location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[30,32] cannot find symbol
  symbol:   class JSchException
  location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[225,32] cannot find symbol
  symbol:   class LsEntry
  location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[53,51] cannot find symbol
  symbol:   class UserInfo
  location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[53,61] cannot find symbol
  symbol:   class UIKeyboardInteractive
  location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[33,25] cannot find symbol
  symbol:   class JSch
  location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[33,41] cannot find symbol
  symbol:   class JSch
  location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[34,25] cannot find symbol
  symbol:   class Session
  location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[45,40] cannot find symbol
  symbol:   class ChannelSftp
  location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[47,26] cannot find symbol
  symbol:   class JSchException
  location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[132,50] cannot find symbol
  symbol:   class LsEntry
  location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[132,30] cannot find symbol
  symbol:   class LsEntry
  location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[191,62] cannot find symbol
  symbol:   variable ChannelSftp
  location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[233,17] cannot find symbol
  symbol:   class SftpATTRS
  location: class com.exlibris.ftp.SFTPUtil
[INFO] 23 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.446 s
[INFO] Finished at: 2019-11-25T08:30:06-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project AlmaRemoteStorageApp: Compilation failure: Compilation failure:
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[15,23] package com.jcraft.jsch does not exist
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[16,35] package com.jcraft.jsch.ChannelSftp does not exist
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[17,23] package com.jcraft.jsch does not exist
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[18,23] package com.jcraft.jsch does not exist
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[19,23] package com.jcraft.jsch does not exist
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[20,23] package com.jcraft.jsch does not exist
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[21,23] package com.jcraft.jsch does not exist
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[22,23] package com.jcraft.jsch does not exist
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[27,17] cannot find symbol
[ERROR]   symbol:   class ChannelSftp
[ERROR]   location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[29,16] cannot find symbol
[ERROR]   symbol:   class ChannelSftp
[ERROR]   location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[30,32] cannot find symbol
[ERROR]   symbol:   class JSchException
[ERROR]   location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[225,32] cannot find symbol
[ERROR]   symbol:   class LsEntry
[ERROR]   location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[53,51] cannot find symbol
[ERROR]   symbol:   class UserInfo
[ERROR]   location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[53,61] cannot find symbol
[ERROR]   symbol:   class UIKeyboardInteractive
[ERROR]   location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[33,25] cannot find symbol
[ERROR]   symbol:   class JSch
[ERROR]   location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[33,41] cannot find symbol
[ERROR]   symbol:   class JSch
[ERROR]   location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[34,25] cannot find symbol
[ERROR]   symbol:   class Session
[ERROR]   location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[45,40] cannot find symbol
[ERROR]   symbol:   class ChannelSftp
[ERROR]   location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[47,26] cannot find symbol
[ERROR]   symbol:   class JSchException
[ERROR]   location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[132,50] cannot find symbol
[ERROR]   symbol:   class LsEntry
[ERROR]   location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[132,30] cannot find symbol
[ERROR]   symbol:   class LsEntry
[ERROR]   location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[191,62] cannot find symbol
[ERROR]   symbol:   variable ChannelSftp
[ERROR]   location: class com.exlibris.ftp.SFTPUtil
[ERROR] /opt/local/scf/AlmaRemoteStorageApp/src/main/java/com/exlibris/ftp/SFTPUtil.java:[233,17] cannot find symbol
[ERROR]   symbol:   class SftpATTRS
[ERROR]   location: class com.exlibris.ftp.SFTPUtil

Thanks,
Kathy

**Comment by ori229** [comment]
Sorry - pom.xml was left out of the commit. Now it's in.
